coverage:
  status:
    project:
      default:
        target: 75%
        threshold: 2%
    patch:
      default:
        target: 70%

ignore:
  - "tests/**"
  - "samples/**"
  - "**/obj/**"
  - "**/bin/**"
